### ISSUE TITLE
regressions and issues

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/tldr#163]
- the daily summary has markdown links but they are displayed in text and not links
<img width="821" alt="Screenshot 2024-01-18 at 7 54 03 PM" src="https://github.com/bitcoinsearch/tldr/assets/755825/aac31c45-720b-419a-9d04-b85bcc381a19">

- the link from active discussions is to individual posts and not the combined summaries
<img width="752" alt="Screenshot 2024-01-18 at 7 55 42 PM" src="https://github.com/bitcoinsearch/tldr/assets/755825/a1ec91e0-dc8c-489a-8a35-b2b2c9576095">

- the author breadcrumb links to the page you are already on. (I don't understand where it is supposed to point or why it is a link at all)
<img width="506" alt="Screenshot 2024-01-18 at 7 56 50 PM" src="https://github.com/bitcoinsearch/tldr/assets/755825/bdd0f617-0448-4f55-9c9a-199de3cef9f1">

- The replies link in the active discussions section points to the original post rather than the history section of the combined summary.

- posts that have no replies are said to have 1 reply (all the other the counts seem to be increased by 1)
<img width="836" alt="Screenshot 2024-01-18 at 7 58 18 PM" src="https://github.com/bitcoinsearch/tldr/assets/755825/5d804dae-0db5-4328-bd82-52e9bda02665">

**Comment by Extheoisah** [comment]
On this:
> the link from active discussions is to individual posts and not the combined summaries

This has always been the behaviour except we want to change that.

> all the other the counts seem to be increased by 1

The `1 reply` tag is off but the multiple replies count are actually accurate. But I think the issue is in the combined summary we start the numbering from 0 not 1. So for 15 replies (as shown in the homepage) it shows the authors from count 0 - 14. We'll synchronise them so the numbering always start from 1.
